[routers]
TEST-RTR-21 ansible_host=198.18.135.21

[switches_core]
TEST-CORE-22 ansible_host=198.18.135.22
TEST-CORE-23 ansible_host=198.18.135.23

[switches_access]
TEST-ACC-24 ansible_host=198.18.135.24
TEST-ACC-25 ansible_host=198.18.135.25

[switches:children]
switches_core
switches_access