---
# Defines every VLAN that must exist across switches.
# 'vlan_id': VLAN number as it appears in 'show vlan brief'
# 'name': exact name configured on the switch

vlans:
  - vlan_id: 100
    name: CORP
  - vlan_id: 150
    name: IOT
  - vlan_id: 200
    name: GUEST
